#+TITLE:Mastering Org-Mode
#+AUTHOR:WLHarvey4
#+EMAIL:wlharvey4@mac.com
#+DATE:<2018-12-09 Sun 22:31>
#+VERSION:{{{version}}}
#+MACRO:version 0.1

#+TEXINFO_FILENAME:mastering-org.info
#+TEXINFO_CLASS: info
#+TEXINFO_HEADER:
#+TEXINFO_POST_HEADER:
#+SUBTITLE:Version {{{version}}} {{{time(%F %R)}}}
#+SUBAUTHOR:
#+TEXINFO_DIR_CATEGORY:Org-Mode
#+TEXINFO_DIR_TITLE:Mastering Org-Mode
#+TEXINFO_DIR_DESC:How to master org-mode in a decade
#+TEXINFO_PRINTED_TITLE:How To Master Org-Mode In A Decade

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:
#+LATEX_HEADER:
#+LATEX_HEADER_EXTRA:
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:
#+LATEX_COMPILER: pdflatex
#+DATE: \today

#+OPTIONS: html-link-use-abs-url:nil html-postamble:auto
#+OPTIONS: html-preamble:t html-scripts:t html-style:t
#+OPTIONS: html5-fancy:nil tex:t
#+HTML_DOCTYPE: xhtml-strict
#+HTML_CONTAINER: div
#+DESCRIPTION:
#+KEYWORDS:
#+HTML_LINK_HOME:
#+HTML_LINK_UP:
#+HTML_MATHJAX:
#+HTML_HEAD:
#+HTML_HEAD_EXTRA:
#+SUBTITLE:
#+INFOJS_OPT:
#+CREATOR: <a href="https://www.gnu.org/software/emacs/">Emacs</a> 26.1 (<a href="https://orgmode.org">Org</a> mode 9.1.14)
#+LATEX_HEADER:

* Glossary
  - ~#+KEY:~ :: *In-buffer setting* ==> See [[https://orgmode.org/org.html#In_002dbuffer-settings][In-Buffer Settings]]

                /In-buffer settings/ start with ‘#+’, followed by a keyword, a colon, and then a
                word for each setting.  There are dozens upon dozens of these.  To see an
                alphabetical list of (most) of them, look in the index under ~#~ ==> [[https://orgmode.org/org.html#Main-Index][#-Index]].
                Unfortunately, not all are in the index.

                You will see numerous /in-buffer settings/ scattered throughout the manual and
                tutorials, but they are not introduced prior, so they can be somewhat cryptic at
                first.

                In addition to /in-buffer settings/, there is another similar construct called
                *OPTIONS* (~#+OPTIONS:~) which is used to set in-buffer settings as well (primarily
                for export settings).  Unfortunately, the manual uses the term 'options' for
                in-buffer settings as well as ~OPTIONS~.

                - ~C-c C-c~ :: activate changes to in-buffer settings
  - TAG (~:tag:~) :: Words delimited by colons (~:~) added to the end of a headline to give extra
                     context.  ==> See [[https://orgmode.org/org.html#Tags][Tags]].  They can be stacked (called a /list of tags/):
                     ~:tag1:tag2:~

                      Tags are normal words containing /letters/, /numbers/, /underscores (_)/,
                      and /ampersands (@)/.
  - PROPERTY (~:PROPERTY:value~) :: A property is a key-value pair associated with an entry.
       Depending on how one is set up, it can be associated with a single entry or with a tree, or
       with every entry in a file.  Like a tag, a property is delimited on both ends by colons, so
       this is a property: ~:A_PROPERTY:Some value~.  The key portion is case-insensitive.
* Editing

* Navigating
