# -*- mode: org; fill-column: 99; -*-

#+TITLE:Mastering Org-Mode
#+AUTHOR:WLHarvey4
#+EMAIL:pinecone062@gmail.com
#+DATE:<2019-03-19 Tue 22:23>
#+VERSION:{{{version}}}
#+MACRO:version 0.4.1

* Glossary

** Agenda

  - Agenda :: Org can select items based on various criteria and display them in a separate
              buffer. Six different [[*View][view types]] are provided, one of which is ~agenda~: like a
              calendar and shows information for specific dates.  The extracted information is
              displayed in a special /agenda/ buffer.

    + Agenda Files :: The information to be shown is normally collected from all /agenda/
                      files, the files listed in the variable ~org-agenda-files~.  If a
                      directory is part of this list, all files with the extension ~.org~
                      in this directory will be part of the list.  Add and remove files
                      from this list using ~C-c [~ and ~C-c ]~.



      #+NAME:reveal-org-agenda-files
      #+BEGIN_SRC elisp :results pp
      org-agenda-files
      #+END_SRC

      #+RESULTS: reveal-org-agenda-files
      : ("/usr/local/dev/programming/Emacs/Org/Mastering-Org/mastering-org.org" "/usr/local/work/workorg/workcases.org" "/Users/lolh/.org/notes.org")

    + Cycling through agenda files :: ~C-,'~ ~(org-cycle-agenda-files)~

    + Switch between buffers :: ~M-x org-switchb <RET>~ ~iswitchb~ like interface

    + Agenda Dispatcher :: The views are created through a dispatcher, which should be bound to a
         [[*Global Keys][global key]]---for example ~C-c a~.  After pressing ~C-c a~, an additional letter is required
         to execute a command.  ~a~ produces a calendar-like /agenda/ view.  ~t~ produces a list of
         ~TODO~ items.  ~m~ produces headlines matching a ~TAGS~ expression.  There are others as
         well.  See [[https://orgmode.org/manual/Agenda-dispatcher.html#Agenda-dispatcher][Agender Dispatcher]].

** Babel
   - Babel :: [[https://orgmode.org/worg/org-contrib/babel/][active code in Org-mode]]

              Babel is Org-mode's ability to execute source code within Org-mode documents.  Babel
              started life as Org-babel, an extension to Org-mode.  It was integrated into the
              Org-mode core at version 7.0. The author of Babel is Eric Schulte. The secondary
              author is Dan Davison.

              [[https://orgmode.org/worg/org-contrib/babel/languages.html][List of supported languages]] with information on requirements, configuration
              instructions, and pointers to language specific documentation.

   - Babel Tutorial :: https://orgmode.org/worg/org-contrib/babel/intro.html

                       An online set of installation and setup instructions, as well as an overview
                       of the main features of Babel, with plenty of examples.

   - Reference Card :: [[https://org-babel.readthedocs.io/en/latest/][Org Babel Reference Card]]

   - Babel Documentation :: https://orgmode.org/manual/Working-with-source-code.html

   - Literate Programming ::

        [[https://www.jstatsoft.org/article/view/v046i03][A Multi-Language Computing Environment for Literate Programming and Reproducible Research]]

        A journal paper providing the most up to date and complete introduction to using Org-mode
        and Babel for Reproducible research and literate programming.

        [[https://caiorss.github.io/Emacs-Elisp-Programming/Org-mode-recipes.html][Literate Programming Recipes]]

        [[http://www.howardism.org/Technical/Emacs/literate-programming-tutorial.html][Introduction to Literate Programming]]

   - Examples and Uses :: [[https://orgmode.org/worg/org-contrib/babel/uses.html][Source Code Blocks: Uses]]

        [[http://eschulte.github.io/org-scraps/][Scraps]]

** Capture

  - Capture :: *Capture* lets you quickly store notes with little interruption of your work
               flow [fn:remember].  Capturing is controlled by ~org-remember.el~.

    + Set Up Capture :: set a default target file for notes, and define a global key for
      capturing new material.
      : (setq org-default-notes-file (concat org-directory "/notes.org"))
      : (define-key global-map "\C-cc" 'org-capture)

    + Use Capture<<capture>> :: ~C-c c~ is the basic command ~(org-capture)~; it has some alternates:

      + ~(org-capture &optional ARG)~ :: ~C-c c~; with a prefix ~C-u C-c c~, find the last stored
           capture; with two prefixes ~C-u C-u C-c c~, visit the last stored capture in a separate
           buffer.  Can also jump to the bookmark ~org-capture-last-stored~.  With a zero prefix
           ~C-0 C-c c~, insert the capture at point.
      + ~(org-capture-finalize)~ :: ~C-c C-c~
      + ~(org-capture-refile)~ :: ~C-c C-w~
      + ~(org-capture-kill)~ :: ~C-c C-k~

[fn:remember] Org’s method for capturing new items is heavily inspired by John Wiegley excellent
~remember.el~ package.]


  - Capture Templates :: You can use templates for different types of capture items, and for
       different target locations.  Because the code is quite complex, you should create new
       templates using the customize interface, using ~C-c c C~.

    See [[https://orgmode.org/manual/Capture-templates.html#Capture-templates][Capture Templates]] for full details

** Category

  - Category :: The /category/ is a broad label assigned to each agenda item.  By default, the
                category is simply derived from the file name.  You can specify a file-wide
                category using the in-buffer setting ~#+CATEGORY: Value~ outside of a heading.  A
                different in-buffer category can be added to a heading, or you can give each entry
                its own category with the ~:CATEGORY:Value~ property.  The AGENDA VIEW uses the
                category as the first item in a line.

** Drawer

  - Drawer (~:DRAWERNAME:~) :: A place to hide content and settings.  A drawer name is delimited by
       colons.  A drawer must be terminated by an ~:END:~ keyword.  Anything can go inside a
       /drawer/ except a heading and another drawer.

       ~C-c C-x d~ :: ~(org-insert-drawer &optional ARG DRAWER)~; interactively insert a drawer at
       point; with an active region, put the region inside a drawer; with a prefix argument, insert
       a /property drawer/ (see [[property-drawer][Property Drawer]]; see [[logbook-drawer][Logbook Drawer]]).

** Footnote

  - Footnote (~[fn:m]~) :: A footnote is started by a /footnote marker/ in square brackets in
       column 0, no indentation allowed. It ends at the next footnote definition, headline, or
       after two consecutive empty lines.  The /footnote reference/ is simply the /marker/ in
       square brackets, inside text.  Markers always start with ~fn:~.

       Footnote Example:
       : The Org homepage[fn:1] now looks a lot better than it used to.
       : ...
       : [fn:1] The link is: https://orgmode.org

       Footnotes may also be *named footnotes*: ~[fn:name]~ (name must be unique).

       Footnames may also be *inline footnotes*: ~[fn:inline definition]~.  This is basically a
       LaTeX-like anonymous footnote where the definition is given directly at the reference point.

       Finally, a hybrid footnote with both a label and an in-line definition, allowing further
       references to the same footnote.
       : [fn:name:a definition]
** Hyperlink

  - Hyperlink :: A link to another place in a file, another file, Usenet article, email, etc.
                 Links are categorized as /internal/ or /external/.  [[info:org#Handling%20links][Handling Links]]

    + Link Format :: =[[link][Description] ]= where [Description] is optional

    + ~C-c l~ :: ~(org-store-link)~ store a link to the current location (because this is a /global
                 command/, you must create a key binding yourself.

      - Org buffers :: cursor on ~<<target>>~; cursor on headline; ~:CUSTOM_ID:~ property;

      - Email News :: link will point to current thing

      - Web browsers :: EWW, W3, W3M link will point to current URL, with page title as description

      - Files :: link will point to the file, with a search string pointing to the contents of the
                 current line; can create custom functions to select the search string.

    + ~C-c C-l~ :: create or edit a link; all links stored during the current session are part of
                   the history; can access them with ~<UP>~ and ~<DOWN>~ (or ~M-p/n~).

    + ~C-u C-c C-l~ :: a link to a file will be inserted; may use file name completion to select
                       the name of the file.  (Force an absolute path with 2 ~C-u~ prefixes).

    + ~C-c C-o~ or ~<RET>~:: follow a link; execute a command in a shell link; run an internal
      search; create a TAGS view; compiles an agenda for date; visit an external file; run an
      external program (based on file extension); to visit without running, call with a ~C-u~
      prefix;

    + ~C-c C-x C-v~ :: ~(org-toggle-inline-image)~

    + ~C-c &~ :: return to calling position (using Org's mark ring)

    + ~C-c %~ :: Push current position onto the mark ring to make for an easy return.

    + ~C-c C-x C-n/p~ :: next/previous link

    + Internal Link :: a link that does not look like a URL is considered an /internal link/

      * custom-id link :: ~[[#my-custom-id] ]~, which links to the entry with the
                          ~:CUSTOM_ID:my-custom-id~ property, which must be unique in the file.

      * text link :: ~[[My Target][description] ]~ performs a text search in the current file.  The
                     preferred match is to a /dedicated target/, which is the text in double angle
                     brackets: ~<<My Target>>~.  If there is no dedicated target, then there will
                     be a search for an exact name: ~#+NAME: My Target~, placed just before the
                     element it refers to.  Note that you must use the ~#+CAPTION:~ keyword.
                     Finally, there will be a search for a headline that is exactly the link text,
                     plus optionally ~TODO~ and tags.

                     Use in-buffer completion to insert a link targeting a headline: ~* abc M-<TAB>~

    + External Link :: Link to a file, website, Usenet, or email message, plus more.  An external
                       link is a URL-like locator, starting with a short identifying string and a
                       colon.  See 4.3 External Links for a list of examples.

      - If the description is a file name or URL that points to an image, HTML export will inline
        the image as a clickable link; if there is no description, that image will be inlined
        into the exported HTML file.

** Key

  - ~#+KEY:~ :: *In-buffer setting* ==> See [[https://orgmode.org/org.html#In_002dbuffer-settings][In-Buffer Settings]]

    /In-buffer settings/ start with ‘#+’, followed by a keyword, a colon, and then a word for each
                setting.  There are dozens upon dozens of these.  To see an alphabetical list of
                (most) of them, look in the index under ~#~.  Unfortunately, not all are in the
                index.

    ==> [[https://orgmode.org/org.html#Main-Index][#-Index]]

    You will see numerous /in-buffer settings/ scattered throughout the manual and tutorials, but
                they are not introduced prior, so they can be somewhat cryptic at first.

    In addition to /in-buffer settings/, there is another similar construct called *OPTIONS*
                (~#+OPTIONS:~) which is used to set in-buffer settings as well (primarily for
                export settings).  /Options/ uses a large set of short, abbreviated key-value pairs
                ([[https://orgmode.org/manual/Export-settings.html#Export-settings][Options]]).  Unfortunately, the manual uses the term 'options' for in-buffer
                settings as well as ~OPTIONS~.

** Keyword

  - Keyword :: A ~TODO~ state, e.g. one of: ~TODO~ ~DONE~.  These are the default states.  You can
               customize the states using ~TODO~ kewords, e.g., ~TODO~ -> ~FEEDBACK~ -> ~VERIFY~ ->
               ~DONE~ | ~VERIFIED~.

               Org offers many facets to this functionality, all of which is configurable.  See
               [[https://orgmode.org/manual/Workflow-states.html#Workflow-states][TODO Keywords]] and [[https://orgmode.org/manual/TODO-extensions.html#TODO-extensions][Extended TODO Keywords]].

** Outline

  - Outline :: Org is implemented on top of Outline mode.  Outlines allow a document to be
               organized in a hierarchical structure.  An overview of this structure is achieved by
               *folding* (/hiding/) large parts of the document to show only the general document
               structure and the parts currently being worked on.

    + ~<TAB>~ :: ~(org-cycle &optional ARG)~

         This function has many different semantic meanings depending upon its context and how many
         arguments precede it.

         When point is at the beginning of a headline, rotate the subtree through 3 different
                 states (called /local cycling/): FOLDED -> CHILDREN -> SUBTREE

         When called with a single prefix ~C-u~, rotate the buffer through 3 states (/global
         cycling/): OVERVIEW -> CONTENTS -> SHOW ALL

         When called with two prefix arguments (~C-u C-u~) switch to the startup visibility.

         When called with three prefix arguments (~C-u C-u C-u~) show the entire buffer, including
                 drawers.

    + ~<S-TAB>~ :: ~(org-shifttab & optional ARG)~

         Global visibility cycling (unless within a table; then ~(org-table-previous-field)~;

** Property

  - PROPERTY (~:PROPERTY:value~) :: A property is a key-value pair associated with an entry.
       Depending on how one is set up, it can be associated with a single entry or with a tree, or
       with every entry in a file.  Like a tag, a property is delimited on both ends by colons, so
       this is a property: ~:A_PROPERTY:Some value~.  The key portion is case-insensitive.

  - Property Drawer (~:PROPERTIES:...:END:~)<<property-drawer>> :: A drawer called ~:PROPERTIES:~,
       inside of which are kept various individual properties.

       ~C-u C-c C-x d~ :: (org-insert-drawer &optional ARG); insert a property drawer below the
       current headline.

  - Logbook Drawer (~:LOGBOOK:...:END:~)<<logbook-drawer>> :: A special drawer to store /state change notes/ and /clock
       times/.  See [[state-change][State Change]].

** Refile

  - REFILE :: Refile or copy /captured/ data (see [[capture][Capture]])

    + ~(org-refile)~ :: ~C-c C-w~ Refile the entry or region at point. This command
                        offers possible locations for refiling the entry and lets you
                        select one with completion.  By default, all level 1 headlines in
                        the current buffer are considered to be targets, but you can have
                        more complex definitions across a number of files using variable
                        ~org-refile-targets~.  This command utilizes many different
                        prefix patterns to alter the semantics.  See [[https://orgmode.org/manual/Refile-and-copy.html#Refile-and-copy][Refile and Copy]].

    + ~(org-copy)~ :: Copying works like refiling, except that the original note is not
                      deleted.

** Tags

   Implement labels and contexts for cross-correlating information by assigning *tags* to
   headlines.  Every headline can contain a list of *:tags:*.

   - Tags :: normal words containing /letters/, /numbers/, /underscores (_)/, and /ampersands (@)/
             delimited by colons =:tag:=.  They can be stacked (called a /list of tags/):
             =:tag1:tag2:=

      ==> See [[https://orgmode.org/org.html#Tags][Tags]]

     + =C-c C-q= :: ~org-set-tags-command~

     + ~C-c C-c~ :: call ~org-set-tags-command~ when on a headline; activate changes to in-buffer
                    settings


   - Inheritance :: All subheadings inherit tags from parent headings

   - =#+FILETAGS:= :: Assign tags to all headings in a file

   - =#+TAGS:= :: Name default tags to choose from for a file

   - =#+STARTUP: noptag= :: disable persistent tags alist


*** Tag Variables

   - ~org-tag-alist~ :: globally defined preferred set of tags

     + /fast tag selection/ mechanism; set globally:
       : (setq org-tag-alist '(("@work" . ?w) ("@home" . ?h) ("laptop" . ?l)))
       mutually exclusive groups:
       : (setq org-tag-alist ''((:startgroup . nil) ("@work" . ?w) ("@home" . ?h) (:endgroup . nil) ("laptop" . ?l)))
       set file locally (*must =C-c C-c= toactivate*):
       : #+TAGS: @work(w) @home(h) @tennisclub(t) labtop(l) pc(p)
       mutually exclusive groups:
       : #+TAGS: { @work(w) @home(h) @tennisclub(t) } laptop(l) pc(p)

       =C-c C-c= works to display a splash window; see [[info:org#Setting%20Tags][manual]] for fine tuning splash window.

       A special interface lists:
       - inherited tags
       - tags in current headline
       - list of all valid tags

       Special keys:
       - =<TAB>= : enter any tag
       - =<SPC>= : clear all tags
       - =<RET>= : accept modified set
       - =C-g=   : abort
       - =q=     : abort (if not assigned)
       - =!=     : turn off mutually-exclusve groups
       - =C-c=   : toggle auto-exit

   - ~org-tag-persistent-alist~ :: globally defined in addition to =#+TAGS=

   - ~org-tag-faces~ :: variable in which to specify special faces for specific tags

   - ~org-use-tag-inheritance~ ::

   - ~org-tags-exclude-from-inheritance~ ::

   - ~org-tags-match-list-sublevels~ ::

   - ~org-agenda-use-tag-inheritance~ ::

   - ~org-tags-column~ ::

   - ~org-fast-tag-selection-single-key~ ::

   - ~org-complete-tags-always-offer-all-agenda-tags~ ::

*** Tag Hierarchy

    Tags can be defined in *hierarchies*.  Defining multiple /group tags/ and nesting them creates
    a *hierarchy*.  Can create a /taxonomy/ of terms to classify nodes.  When searching for a group
    tag, the search returns all members of the group and subgroups.

    : #+TAGS: [ GTD : Control Persp ]
    : #+TAGS: [ Control : Context Task ]
    : #+TAGS: [ Persp : Vision Goal AOF Project ]

    - GTD
      + Persp
        - Vision
        - Goal
        - AOF
        - Project
      + Control
        - Context
        - Task


    #+BEGIN_EXAMPLE
         (setq org-tag-alist '((:startgrouptag)
                           ("GTD")
                           (:grouptags)
                           ("Control")
                           ("Persp")
                           (:endgrouptag)
                           (:startgrouptag)
                           ("Control")
                           (:grouptags)
                           ("Context")
                           ("Task")
                           (:endgrouptag)))
    #+END_EXAMPLE

** ~TODO~

  - ~TODO~ STATE CHANGE<<state-change>> :: keep track of when a state change occurred and maybe
       take a note about this change.  You can either record just a timestamp, or a time-stamped
       note for a change.  These records will be inserted after the headline as an itemized list,
       newest first.

       To keep the notes hidden and out of the way, place them into a special drawer called
       ~:LOGBOOK:~.  [[logbook-drawer][Logbook Drawer]]   Globally customize the variable ~org-log-into-drawer~ to get
       this behavior.  You can also set a property called ~:LOG-INTO-DRAWER:DrawerName~.

       ~C-c C-z~ :: ~(org-add-note)~  add a note to the current entry

       To time-stamp when a ~TODO~ is changed to ~DONE~, set the variable ~org-log-done~ to the
       value of ~time~, or use the in-buffer setting of ~#+STARTUP: logdone~.  A line ~CLOSED:
       [timestamp]~ will be inserted.

       To also record a note when cycling a ~TODO~ to ~DONE~, set the variable ~org-log-done~ to
       the value ~note~ instead, or add an in-buffer setting of ~#+STARTUP: lognotedone~.

       To customize special logging for other state changes, see [[https://orgmode.org/manual/Tracking-TODO-state-changes.html#Tracking-TODO-state-changes][Tracking TODO State Changes]]

  - TAG (~:tag:~) :: Words delimited by colons (~:~) added to the end of a headline to give extra
                     context.
    ==> See [[https://orgmode.org/org.html#Tags][Tags]].  They can be stacked (called a /list of tags/): ~:tag1:tag2:~

    Tags are normal words containing /letters/, /numbers/, /underscores (_)/, and /ampersands (@)/.

    + ~C-c C-c~ :: activate changes to in-buffer settings

  - Clocking Time :: Clock the time you spend on a specific task in a project.  When you start
                     working on an item, start the clock.  When you stop, or when you mark ~DONE~,
                     stop the clock.  The corresponding time interval is recorded.  Org will also
                     comput the total time spent on each subtree of a project.  [[info:org#Clocking%20commands][Clocking Commands]]

                     Consider creating global key bindings for ~(org-clock-out)~ and
                     ~(org-clock-in-last)~ 

    + ~C-c C-x C-i~ :: ~(org-clock-in)~ --- inserts the ~CLOCK~ keyword together with a timestamp.

      * ~C-u C-c C-x C-i~ :: select from a list of recently clocked tasks.

      * ~C-u C-u C-c C-x C-i~ :: clock into the task at point and mark it as the /default task/; the
           /default task/ will then be available with ~d~ when selecting a clocking task.

      * ~C-u C-u C-u C-c C-x C-i~ :: force continuous clocking by starting the clock when the last
           clock is stopped.

    + ~C-c C-x C-o~ :: ~(org-clock-out)~ --- stop the clock; inserts another timestamp at the same
                       location where the clock was started.  Computes the resulting time and
                       inserts it.  Have the option of inserting an additional note using the
                       variable: ~org-log-note-clock-out~, or ~#+STARTUP: lognoteclock-out~.

    + ~C-c C-x C-x~ :: ~(org-clock-in-last)~ --- reclock the last clocked task.

      * ~C-u C-c C-x C-x~ :: select the task from the clock history

      * ~C-u C-u C-c C-x C-x~ :: force continuous clocking by starting the clock when the last clock
           is stopped.

    + ~C-c C-x C-e~ :: ~(org-clock-modify-effort-estimate)~

    + ~C-c C-c~ or ~C-c C-y~ :: ~(org-evaluate-time-range)~

    + ~C-S-<up/down>~ :: ~(org-clock-timestamps-up/down)~ --- both timestamps; clock duration
         remains the same

    + ~S-M-<up/down>~ :: ~(org-timestamp-up/down)~ --- timestamp at point, and next or previous

    + ~C-c C-t~ :: ~(org-todo)~ --- changes ~TODO~ to ~DONE~ and stops clock

    + ~C-c C-x C-q~ :: ~(org-clock-cancel)~

    + ~C-c C-x C-j~ :: ~(org-clock-goto)~ --- jumpt to headline of currently clocked-in task

      * ~C-u C-c C-x C-j~ :: select the target task from a list of recently clocked tasks

    + ~C-c C-x C-d~ :: ~(org-clock-display)~ --- display time summaries for each subtree in the
                       current buffer.

    + ~l~ :: in the agenda, ~l~ key shows which tasks have been worked on or closed in a day

** View
 - An organized view of specific types of items through a collection process across all org files.
   1. agenda view --- dated items
   2. todo view --- action items
      + ~C-c a t~ ~(org-todo-list)~ global todo list
      + ~C-c a T~ specific todo keyword
   3. match view --- headlines based upon tags, properties, todo states
      + ~C-c a m~ ~(org-tags-view)~
      + ~C-c a M~ specific tags
   4. search view --- entries with specified keywords
      + ~C-c a s~ ~(org-search-view)~
   5. stuck projects view --- projects that cannot ``move''
   6. custom view --- special searches and combinations of views
      + ~C-c a #~ ~(org-agenda-list-stuck-projects)~

* Org Setup

** Global Keys

The three Org commands:

- ‘org-store-link’
- ‘org-capture’
- ‘org-agenda’

{{{noindent}}} ought to be accessible anywhere in Emacs, not just in Org buffers.
To that effect, you need to bind them to globally available keys, like the ones reserved for users,
[[info:elisp#Key%20Binding%20Conventions][Key Binding Conventions]],

{{{noindent}}} i.e., sequences beginning with =C-c= and then a letter (upper or lower case).  Here
are suggested bindings:

- =C-c a= :: ~org-agenda~   ~(global-set-key (kbd "C-c a") 'org-agenda)~

- =C-c c= :: ~org-capture~  ~(global-set-key (kbd "C-c c") 'org-capture)~

- =C-c l= :: ~org-store-link~ ~(global-set-key (kbd "C-c l") 'org-store-link)~

** Agenda and Capture Setup

   - ~org-directory~: ::
     Default location in which to look for Org files (originally =$HOME/org=).  Currently
        =$HOME/.org=.  It is used when:
     1. a capture template specifies a target file (no absolute path)
     2. the value of variable ~org-agenda-files~ is a single file

   - ~org-agenda-files~: ::
     The files to be used for agenda display.  It is originally empty.
     - If an entry is a directory, then all org-files in it will be part of the file list.
     - If the value of the variable is a single file name, this file can contain a list of agenda
       files, which can be given relative to ~org-directory~.  Tilde-expansion and ENVIRONMENT
       variable substitution is also made.
     - Entries may be added to and removed from this list with
       - ~M-x org-agenda-file-to-front~
       - ~M-x org-remove-file~

   - ~org-default-notes-file~: ::
        Default target for storing notes.  It is a fallback file for ~org-capture~, for templates
        that do not specify a target file.
     - Original value was: ~$HOME/.notes~
     - Current value is: =$HOME/.org/notes.org=

   - =C-c c= ~(org-capture)~: ::
                       Capture something using a template from ~org-capture-templates~ and file
                       it.  The captured text is inserted at its target location and an indirect
                       buffer is opened allowing you to edit it.  When done, =C-c C-c= lets you
                       continue with your work.
     - =C-u C-c c= GOTO file without capturing anything

   - ~org-capture-templates~: ::
        Templates for the creation of new entries.  It's default value is =nil=.  Most target
        specifications contain a file name.  If that file name is the empty string, it defaults to
        ~org-default-notes-file~.  When an absolute path is not specified for a target, it is taken
        as relative to ~org-directory~.
     - [[help:org-capture-templates][Documentation]]

** Initial Visibility

- By default, initial global state is OVERVIEW (show only top-level headlines)
  + ~C-u C-u <TAB>~ switch to startup visibility state as determined by ~org-startup-folder~
    variable and VISIBILITY properties.
  + ~org-cycle-global-at-bob~ set to =t=, can use ~<TAB>~ to cycle when point is on the first line

- When ~org-agenda-inihibit-startup~ is non-=nil=, Org does not honor the default visibility state
  when opening a file for the agenda (to speed things up).  It is by default set to =nil=.

- configure with ~org-startup-folded~, or on a per-file basis with =#+STARTUP:=, or per-item basis
  with =VISIBILITY= property.

  Possible values for the first two are:
  + overview|fold
  + content|
  + showall|nofold
  + showeverything

- org startup options on a per-file basis chosen by =#+STARTUP:= option.

- Visibility property for individual entries;

  =#+VISIBILITY: folded | children | content | all=

- ~C-u C-u <TAB>~ Switch to startup visibility state

- ~org-catch-invisible-edits~ can be used to help prevent unintended edits;

* Basics

** Org Mode Basics

- http://www.star.bris.ac.uk/bjm/org-basics.html

** Headings

** Todos

* Editing

* Navigating

* Todos

  TODO items are an integral part of the notes file, and intended to be integrated directly while
  taking notes.  Simply mark an entry as being a TODO item, and the entire context from which the
  TODO item emerged is always present.  While your notes become scattered throughout your files,
  Org-mode provides methods to give you an overview of all the things that you have to do.

  - A heading becomes a TODO item when it starts with =TODO=

  - =C-c C-t= ~(org-todo)~: Rotate the TODO state; if fast selection is on (it is), prompt for a
    keyword, but only after fast access keys have been assigned (not done by default).

  - ~S-M-<RET>~: Insert a new TODO entry below

  - ~S-<RIGHT> S-<LEFT>~ : Cycle through multiple keywords

  - =C-c / t= ~(org-show-todo-tree)~: View TODO items in a sparse tree.

  - =C-c / T=: Search for a specific TODO, or a list =KWD1|KWD2=

  - =C-u C-u C-c / t=: Find all TODO states, both done and not done.

  - ~M-x org-agenda t~ ~(org-todo-list)~: Show the global TODO list.

** =TODO= Variables

   - ~org-todo-keywords~ ::
        List of TODO entry keyword sequences and their interpretation.

        Original value is: ~((sequence "TODO" "DONE"))~

   - ~org-use-fast-todo-selection~ ::
        Only works when access keys have actually been assigned by the user.

        Non-nil means use the fast todo selection scheme with ‘C-c C-t’.  When nil, fast selection
        is never used.

        When =prefix=, use fast selection scheme when called with a prefix arg, =C-u C-c C-t=

        When =t=, when calling with a prefix, force cycling of TODO state.

   - ~org-todo-state-tags-triggers~ ::
        Tag changes that should be triggered by TODO state changes.  A list.

* Agenda

** Global TODO List

   The global TODO list contains all unfinished TODO items formatted and collected into a single
   place.

   - =M-x org-agenda t= ~(org-todo-list)~: ::
     ~(org-agenda)~ starts the agenda dispatcher.  Dispatch agenda commands to collect entries to
        the agenda buffer.

     =t= means to show the global TODO list.  This collects the TODO items from all agenda files (see Agenda
        Views::) into a single buffer.

     =T= or =C-u= allows you to select a specific TODO keyword or several using =|=

* Capture

  Quickly store notes in the flow.  Based upon John Wiegley's =Remember= package.

** Setup

   - Set a default target file for notes
     : (setq org-default-notes-file (concat org-directory "/notes.org"))

   - Define a global key for capturing new material.  See Org Activation
     : (global-set-key (kbd "C-c c") 'org-capture)

** Using

   - ORG-CAPTURE :: Display the capture templates menu
     : ~C-c c: (org-capture)~

     If you have templates defined, it offers these templates for selection; otherwise, use a new
     Org outline node as the default template.  It inserts the template into the target file and
     switches to an indirect buffer narrowed to this new node.  You may then insert the information
     you want.

     You can also call =capture= from the *agenda*
     : k c

     Any timestamps inserted by the selected capture template defaults to the date at point in the
                    agenda

   - ORG-CAPTURE-FINALIZE :: Resume your work
     : ~[C-u] C-c C-c: (org-capture-finalize)~

     - Return to the window configuration before the capture process and resume your work.

     - When called with a prefix argument, finalize and then jump to the captured item.

   - ORG-CAPTURE-REFILE :: Refile the note to an appropriate place
     : ~C-c C-w: (org-capture-refile)~

     This is a normal refiling command that will be executed; =point='s position is important.
     Make sure =point= is on the appropriate parent node.  See [[info:org#Refile%20and%20Copy][Refile and Copy]].

     Any prefix argument given to this command is passed on to the ~org-refile~ command.

   - ORG-CAPTURE-KILL :: Abort
     : ~C-c C-k: (org-capture-kill)~

     Abort the capture procedure and return to the previous state.

** Capture Templates

   You can use templates for different types of capture items, and for different target locations.
   Create templates using the =customize= interface.  Customize the variable
   ~org-capture-templates~.

*** Elements

    Each entry in org-capture-templates is a list with the following items:

    - keys ::
        the key(s) that select the template, as string characters (``a'' to use a single key)
      (``bt'' to use two keys).

      When using several keys, keys using the same prefix key must be sequential in the list and
      preceded by a 2-element entry explaining the prefix key:
      : ("b" "Templates for marking stuff to buy")
      If you do not define a template for the C key, this key opens the Customize buffer for this
      complex variable.

    - description ::
                     A short string describing the template

    - type ::
              The type of entry, a symbol.

      - ~entry~

        An Org mode node, with a headline. Will be filed as the child of the target entry or as a
        top-level entry. The target file should be an Org file.

      - ~item~

        A plain list item, placed in the first plain list at the target location. Again the target
        file should be an Org file.

      - ~checkitem~

        A checkbox item. This only differs from the plain list item by the default template.

      - ~table-line~

        A new line in the first table at the target location. Where exactly the line will be
        inserted depends on the properties ~:prepend~ and ~:table-line-pos~

      - ~plain~

        Text to be inserted as it is.

    - target ::

      Specification of where the captured item should be placed.

      - targets usually define a node and entries will become children of this node.

      - other types will be added to the table or list in the body of this node.

      - most target specifications contain a file name.  If that file name is the empty string, it
        defaults to ~org-default-notes-file~.

      - a file can also be given as a variable or as a function called with no argument.

      - when an absolute path is not specified for a target, it is taken as relative to
        ~org-directory~.

      Valid values are:

      - ~(file "path/to/file")~ ::
           Text will be placed at the beginning or end of that file.

      - ~(id "id of existing org entry")~ ::
           Filing as child of this entry, or in the body of the entry.

      - ~(file+headline "filename" "node headline")~ ::
           Fast configuration if the target heading is unique in the file.

      - ~(file+olp "filename" "Level 1 heading" "Level 2" ...)~ ::
           For non-unique headings, the full path is safer.

      - ~(file+regexp "filename" "regexp to find location")~ ::
           Use a regular expression to position point.

      - ~(file+olp+datetree "filename" [ "Level 1 heading" ...])~ ::
           This target creates a heading in a date tree for today’s date.  If the optional outline
           path is given, the tree will be built under the node it is pointing to, instead of at
           top level.

      - ~(file+function "filename" function-finding-location)~ ::
           A function to find the right location in the file.

      - ~(clock)~ ::
                     File to the entry that is currently being clocked.

      - ~(function function-finding-location)~ ::
           Most general way: write your own function which both visits the file and moves point to
           the right location.

    - template

    - properties

*** Explansion

*** In Context

** Org Capture Customization
*** Org Capture Group

    Options concerning capturing new entries.

    - Org Directory
    - Org Default Notes File
    - Org Reverse Note Order
    - Org Datetree Add Timestamp

    - Org Capture Bookmark
    - Org Capture Templates
    - Org Capture Templates Contexts
    - Org Capture Use Agenda Date
    - Org Capture Prepare Finalize Hook
    - Org Capture Before Finalize Hook
    - Org Capture After Finalize Hook

*** Org Refile Group

    - Org Refile Targets
    - Org Log Refile
    - Org Outline Path Complete In Steps
    - Org Refile Active Region Within Subtree
    - Org Refile Allow Creating Parent Nodes
    - Org Refile Target Verify Function
    - Org Refile Use Cache
    - Org Refile Use Outline Path

* Examples

** Examples and Cookbook

- [[http://ehneilsen.net/notebook/orgExamples/org-examples.html][Emacs org-mode examples and cookbook]]

* Issues

** ~jit-lock~ Interfering with ~org-goto~

   #+CINDEX:jit-lock
   - ``Not enabling jit-lock: it does not work in indirect buffer.''

     Received when running the command ~org-goto~ (i.e., =C-c C-j=)

     [[https://emacs.stackexchange.com/questions/36374/jit-lock-message-it-does-not-work-in-indirect-buffer-does-not-allow-me-to-use][jit-lock message...]]

     #+BEGIN_QUOTE
     If someone came to the same issue (or related), know that I solved it by not loading twice org
     from different packages (Elpa and Melpa) in Emacs.
     -- [[https://emacs.stackexchange.com/users/15574/rafael-nagel][Rafael Nagel]]
     #+END_QUOTE

     - ~jit-lock.el~ :: Just-in-time fontification, triggered by C redisplay code.

       - ~(defun jit-lock-mode (arg) ...)~ :: ``Toggle Just-in-time Lock mode''

            When in an indirect buffer, ~jit-lock-mode~ won't work, and this message appears.  That
            begs the question why it appears during a call to ~org-goto~.

     - Resolution ::
                     My setup included an ~org~ directory inside of MacPorts EmacsMac
                     ~Contents/Resources/lisp/~, as well as an ~org-9.2.2~ inside of my
                     ~/.emacs.d/~ which I installed yesterday.  Upon removing the ~org~ directory
                     and restarting, the error message no longer appeared and ~org-goto~ worked.
                     No idea why problem occurred other than my system is loading too many packages
                     because of the duplication.  <<mult-load-dirs>>This issue should probably be
                     investigated.

     - Note :: *Important* you need to do this [install new Org-mode] in a session where no =.org=
               file has been visited, i.e., where no Org built-in function have been
               loaded. Otherwise autoload Org functions will mess up the
               installation.[fn::https://orgmode.org/manual/Installation.html]] I probably
               installed a new Org-mode after first visiting an org-file and ``messed things up.''

*** TODO Do Multiple Load Directories Interfere With Each Other

    See [[mult-load-dirs][mult-load-dirs]]

* Blogging with Org

  - [[https://explog.in/][expLog]] & https://explog.in/config.html

  - [[https://cestlaz.github.io/posts/using-emacs-35-blogging/][Using Emacs 35 - Blogging]]

  - [[https://www.reddit.com/r/emacs/comments/857ab1/blogging_with_emacs/][Hugo also has good direct support for org-mode]]

    #+BEGIN_QUOTE
    Anyhow, if it's any comfort, hugo is a really fast static site generator that live updates the
    browser as soon as I C-x C-s my Org file (which auto-triggers the export to .md via ox-hugo)
    #+END_QUOTE

    - [[https://github.com/kaushalmodi/ox-hugo][ox-hugo]]

      I develop an Org exporter called =ox-hugo= which is basically a Markdown (with bits and
      pieces of HTML where Markdown falls short) exporter + TOML/YAML front-matter generator for
      Hugo static sites.  In the process of supporting basically the whole of the Org syntax that I
      know of, and making any Org document exportable almost in par with ox-html, I ended up with
      this [[https://github.com/kaushalmodi/ox-hugo/blob/master/test/site/content-org/all-posts.org][humongous test file]]. It covers probably every niche of Org syntax that I or folks who
      filed issues on the repo could think of (a recent one being.. variations in Org syntax for
      inline vs standalone images, hyperlinked vs not, with/without HTML target attribute being set
      via =#+ATTR_HTML=, with/without captions). I am mentioning that file with hopes that orga is
      able to support all kinds of Org syntax in that. Many tests in there are for testing the Hugo
      front-matter export, but majority of that test file should work for your project too.  In
      addition, how does orga support subtree properties, tags, etc which is critical for folks
      using a single Org file (like that test file) to store all their Org documents organized as
      subtrees (instead of having a physical Org file for each document)?  Once again, great to see
      more Org mode out in the wild :)

    - [[http://www.modernemacs.com/post/org-mode-blogging/][An Emacs Blogging Workflow]]

      Hugo is a static site generator. It natively supports org-mode, builds fast, and has live
      reloading.

  - [[http://donw.io/post/github-comments/][Using Github for Comments]]

  - [[https://github.com/bastibe/org-static-blog][ORG-STATIC-BLOG]]

  - [[https://github.com/novoid/lazyblorg][lazyblorg – blogging with Org-mode for very lazy people]]

  - [[https://xiaoxinghu.github.io/orgajs/][ORGA]]

    - [[https://github.com/xiaoxinghu/orgajs][orgajs on Github]]

    - [[https://github.com/xiaoxinghu/gatsby-orga][gatsby orga starter project]]

      - [[https://www.reddit.com/r/orgmode/comments/7wjmwr/orga_the_ultimate_orgmode_parser_in_javascript/][Orga the Ultimate org-mode parser in JavaScript]]

    - [[http://endlessparentheses.com/how-i-blog-one-year-of-posts-in-a-single-org-file.html][How I blog: One year of posts in a single org file]]

      *When this blog was conceived, I decided that I wanted it to be entirely contained in a
      single org file*, and that this would also be my Emacs init file.... Before anything else, it
      should go without saying that the content of the posts is written in org-mode. The engine I
      use for exporting is a large wrapper around ox-jekyll, and the posts are all pushed to Github
      and rendered by their built-in Jekyll support.

      - <<single-file>>Why keep a blog in [[single-file-fail][a single file]]?

      First of all because org, once you learn its knobs and bobs, is just plain powerful.... This
      is a small difference, but it applies all around. If I want to link to a previous post, I
      find it with C-c C-j and then move back with C-u C-SPC, all without leaving the buffer. When
      I look at the posts list, the tags are listed right beside the title, I don’t have to open a
      file to see them.... You see, if posts were separate files I would have to copy the snippets
      to a separate org file, and then write about them there, and then export them to Jekyll. In
      this scenario, I just know I would eventually change some snippet (a healthy init file is a
      fluid creature) and forget to update the corresponding org file, and the thought of leaving
      out-dated code lying around sent a chill through my spine. Not to mention, this whole flow of
      “init file → org post → jekyll post” has one layer too many for my taste, and redundancy is
      an evil I slay with a chainsaw.

    - [[https://github.com/yoshinari-nomura/org-octopress][Org-octopress – org-mode in octopress.]]

      Org-octopress is a package to help users those who want to write blog articles in org-style
      using Octopress (or Jekyll).

    - [[https://www.sadiqpk.org/blog/2018/08/08/blogging-with-org-mode.html][Blogging with Emacs org-mode]]

      <<single-file-fail>>All pages of this website has been designed in org-mode. Not just this
      blog. The [[https://gitlab.com/sadiq/sadiq.gitlab.io][repository]] contain source code for the complete website.... For about a year, I
      have been trying to find a suitable workflow to blog using Emacs org-mode. *My idea was to
      put all articles (posts) in [[single-file][a single org file]], which failed misserably* for the following
      reasons:

      - The default org-mode html export is designed to work on seperate files. So single file org
        export requires custom code which I don't want to write.

      - I wish to link to the source org file from each html article, which is not possible if
        every article is written in a single file.

      - Last year, I did write around 500 lines of code, which worked. Pretty much all of them were
        unmaintainable hacks. A few days back, I gave it a try again. This time, with a different
        design:

      - Each article is written in seperate org files, with dated directory names. Eg.: A
        hello-world.org file in 2018/08/08 dir for Hello World article.

      - Manually created blog index and atom feeds so that I don't have to wait another year to
        pass the salt.

    - [[https://orgmode.org/worg/org-blog-wiki.html][Blogs and Wikis with Org]]

    - [[https://orgmode.org/worg/org-web.html][Web Pages Made with Org-Mode]]

    - [[https://orgmode.org/worg/org-tutorials/org-publish-html-tutorial.html][Publishing Org-mode files to HTML]]

    - [[https://justin.abrah.ms/emacs/orgmode_static_site_generator.html][Writing a static site generator using org-mode.]]

      This site is now generated through org-mode, an emacs library which is used for
      outlining. The generation of the HTML lies in the export functionality of outlines. The
      benefits of this system is that its easy, uses a tool that I'm already familiar with, and
      extensible.

      The heart of my blog lies in org-modes export format. You can find the documentation for it here. This post, currently looks something like the picture above. Standard org-mode stuff.

      The exporting stuff lives in a small amount of elisp (which is in a non-exported node of my
      ~index.org~ (which turns into ~index.html~)). When I export my org project, it publishes via
      tramp to my server's web root.

    - [[https://justin.abrah.ms/emacs/literate_programming.html][Literate programming with org-babel]]

    - [[https://pavpanchekha.com/blog/org-mode-publish.html][Using Org-mode to Publish a Web Site]]

      This blog is written with Org-mode from Emacs, and deployed using a git hook.

    - [[http://danamlund.dk/emacs/orgsite.html][Example of making and managing a website with emacs org-mode]]

    - [[https://trashbird1240.wordpress.com/2012/01/17/set-up-a-website-using-emacs-org-mode/][Set up a website using Emacs’ Org Mode]]

    - [[https://jgkamat.gitlab.io/blog/website1.html][Creating A Blog in Org Mode]]

      Org is a very powerful tool, but most of the org setups I've seen hasn't used it to its full
      potential. This website is one example of a complex, multi-page project built in org. This
      post is a 'brief' overview of how it was created.

    - [[https://ogbe.net/blog/blogging_with_org.html][Blogging using org-mode (and nothing else)]]

      Obviously, the Org publishing feature was all that I needed. I whipped up a nice little
      configuration that produces this website from a set of Org source files, some custom CSS and
      HTML, and some custom Elisp.

    - [[https://bastibe.de/2013-11-13-blogging-with-emacs.html][Blogging with Emacs]]

    - [[https://thibaultmarin.github.io/blog/posts/2016-11-13-Personal_website_in_org.html][Personal website in org]] <<

      This post describes the configuration for this website, which is statically generated using
      emacs and org-mode. Org-mode's publishing functionality is used to generate the HTML content
      from source org files.

    - [[http://www.bobnewell.net/publish/35years/orgpublish.html][Publishing with Org-Publish]]

    - [[https://www.baty.net/2015/publishing-my-notes-using-org-mode/][Publishing My Notes Using Org Mode]]

* Variables

- ~org-agenda-dim-blocked-tasks~ ::

     Non-=nil= means dim blocked tasks in the agenda display.  Default is non-=nil=.  While this
     causes some overhead during agenda construction, it can be used to advantage.
     [[help:org-agenda-dim-blocked-tasks]]

- ~org-agenda-inhibit-startup~ ::

     Default value is =nil=.

     When =t=, inhibit startup when preparing agenda buffers (visibility state is not set).  Also
     ignore =#+STARTUP:= setting when =t=.  The point of this variable is to speed up agenda
     commands when Org files grow in size and number.

- ~org-agenda-show-inherited-tags~ ::

     Non-nil means show inherited tags in each agenda line.  Default value is =t=.  May be set to a
     list of agenda types (same as ~org-agenda-use-tag-inheritance~).  When =nil=, never show
     inherited tags in agenda lines.

     When this option is set to ‘always’, it takes precedence over ‘org-agenda-use-tag-inheritance’
     and inherited tags are shown in every agenda.

- ~org-agenda-use-tag-inheritance~ ::

     Allowed values are one or more of:

  + =todo=
  + =search=
  + =agenda=

  Setting this option to =nil= will speed up non-tags agenda views /a lot/.

  List of agenda view types where to use tag inheritance.  The default value sets tags in every
     agenda type, i.e., =(todo search agenda)=.  You may want the agenda to be aware of the
     inherited tags anyway, e.g. for later tag filtering.

  This variable has no effect if ‘org-agenda-show-inherited-tags’ is set to ‘always’.  In that
     case, the agenda is aware of those tags.

- ~org-catch-invisible-edits~ ::

  + =nil=: do not check; just do invisible edits.  DEFAULT
  + =error=: throw an error and do not edit
  + =show=: make point visible, and do the requested edit
  + =show-and-error=: make point visible, then throw an error and abort.
  + =smart=: make point visible; do edit in some cases; basically, this allows insertion and
    backward-delete right before ellipses.

     Check if in invisible region before inserting or deleting a character.

- ~org-cycle-emulate-tab~ ::

     Default value is =t=.

     Where should ~org-cycle~ emulate ~<TAB>~.
     + =nil=
     + =white= complete white lines
     + =whitestart= beginning of white lines before first char
     + =t= everywhere except headline
     + =exc-hl-bol= everywhere except start of headline
- ~org-cycle-global-at-bob~ ::

     When non-=nil=, ~<TAB>~ at very beginning of file (not on a headline), runs global cycling.

     *NOTE:* This works even if the first line holds a mode line.

- ~org-insert-mode-line-in-empty-file~ ::

     When non-=nil= and ~org-mode~ is called interactively on an empty file, insert =-*- mode: org
     -*-= into the first line.

- ~org-startup-folded~ ::

     Non-=nil= means entering Org mode will switch to OVERVIEW.

- ~org-tags-exclude-from-inheritance~ ::

     List of tags that should never be inherited.  Default value is =nil=.  Opposite is
     ~org-use-tag-inheritance~.

- ~org-tags-match-list-sublevels~ ::

     Non-=nil= means list also sublevels of headlines matching a search.  Default value is =t=.

     When set to the symbol ‘indented’, sublevels are indented with leading dots.

     Setting this variable to =nil= causes subtrees of a match to be skipped.

     Applies to tags and property searches, and to stuck projects.

     *NOTE:* This variable is semi-obsolete and probably should always be true.  It is better to
     limit inheritance to certain tags using the variables ‘org-use-tag-inheritance’ and
     ‘org-tags-exclude-from-inheritance’.

- ~org-use-tag-inheritance~ ::

     Non-=nil= means tags in levels apply also for sublevels.  Default value is =t=.  If this
     option is =t=, a match early-on in a tree can lead to a large number of matches in the subtree
     when constructing the agenda or creating a sparse tree.  If you only want to see the first
     match in a tree, see ~orgs-tags-match-list-sublevels~.

     When =nil=, only the tags directly given in a specific line apply there.

     May be a list of tags to be inherited, or a regexp to match tags.

* Commands

- ~(org-cycle &optional ARG)~ ::

      ~<TAB>~ Cycle the subtree visibility.

      ~C-u <TAB>~ Global cycling, i.e., ~<S-TAB>~

      ~C-u C-u <TAB>~ Switch to initial visibility

- ~(org-global-cycle &optional ARG)~ ::

     ~<S-TAB>~ | ~<C-u <TAB>~ Cycle the global visibility.

     ~C-<N> <TAB>~ Show contents up to N levels.

* Index
  :PROPERTIES:
  :index:    cp
  :END:

* EXPORT SETTINGS                                                  :noexport:

** OPTIONS

   #+OPTIONS: html-link-use-abs-url:nil html-postamble:auto
   #+OPTIONS: html-preamble:t html-scripts:t html-style:t
   #+OPTIONS: html5-fancy:nil tex:t
   #+INFOJS_OPT:

** GENERAL

   #+CREATOR: <a href="https://www.gnu.org/software/emacs/">Emacs</a> 26.1 (<a href="https://orgmode.org">Org</a> mode 9.1.14)

** TEXINFO EXPORTS

   #+TEXINFO_FILENAME:mastering-org.info
   #+TEXINFO_CLASS: info
   #+TEXINFO_HEADER:
   #+TEXINFO_POST_HEADER:
   #+SUBTITLE:Version {{{version}}} {{{time(%F %R)}}}
   #+SUBAUTHOR:
   #+TEXINFO_DIR_CATEGORY:Org-Mode
   #+TEXINFO_DIR_TITLE:Mastering Org-Mode
   #+TEXINFO_DIR_DESC:How to master org-mode in a decade
   #+TEXINFO_PRINTED_TITLE:How To Master Org-Mode In A Decade

** LATEX EXPORTS

   #+LATEX_CLASS: article
   #+LATEX_CLASS_OPTIONS:
   #+LATEX_HEADER:
   #+LATEX_HEADER_EXTRA:
   #+DESCRIPTION:
   #+KEYWORDS:
   #+SUBTITLE:
   #+LATEX_COMPILER: pdflatex

** HTML EXPORTS

   #+HTML_DOCTYPE: xhtml-strict
   #+HTML_CONTAINER: div
   #+DESCRIPTION:
   #+KEYWORDS:
   #+HTML_LINK_HOME:
   #+HTML_LINK_UP:
   #+HTML_MATHJAX:
   #+HTML_HEAD:
   #+HTML_HEAD_EXTRA:
   #+SUBTITLE:

** MACROS

#+MACRO:noindent @@texinfo:@noindent@@

